version: '3'

services:
  app:
    build:
      context: ./app/
    env_file:
      - .env
    volumes:
      - ./app/:/opt/app/
    ports:
      - 127.0.0.1:8000:8000
    command: bash -c "uvicorn  main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  py-linters:
    build:
      context: ./py-linters/
    image: py-linters:latest
    volumes:
      - ./py-linters/pyproject.toml:/opt/linters/pyproject.toml
      - ./py-linters/poetry.lock:/opt/linters/poetry.lock
      # mount source code to check a code with linter running inside a container
      - ./app:/app
    command: 'echo Skipped'
volumes:
  postgres_data: