version: '3'

services:
  backend:
    build:
      context: ./backend/
    volumes:
      - ./backend:/opt/app/
    ports:
      - 127.0.0.1:8000:8000
    command: bash -c "uvicorn  main:app --host 0.0.0.0 --port 8000"

    depends_on:
      - postgres
  postgres:
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: